### ISSUE TITLE
请教接口问题

### ISSUE THREAD

**Issue by dev-J-Ariza** [Zoutianjian/Beijing_Bus_realtime_query#1]
能否请教一下 `http://www.bjbus.com/api/api_etastation.php?` 这个接口是怎么抓到的？
还有token是怎么获取到的？
谢谢！

**Comment by Zoutianjian** [comment]
额，这个数据源其实相对来说非常地简单（有效信息也非常有限），北京公交官网上的实时查询 
http://www.bjbus.com/home/fun_rtbus.php?uSec=00000160&uSub=00000162 (但愿过段时间别被封禁)
直接使用实时查询应该就行，浏览器F12一下就可以查看，token也能看见........(token每过一段会更新，建议时常去原网站看看)
（这就是一个 GUI 的小作业，更多是写着玩儿的

**Comment by dev-J-Ariza** [comment]
> 额，这个数据源其实相对来说非常地简单（有效信息也非常有限），北京公交官网上的实时查询
> http://www.bjbus.com/home/fun_rtbus.php?uSec=00000160&uSub=00000162 (但愿过段时间别被封禁)
> 直接使用实时查询应该就行，浏览器F12一下就可以查看，token也能看见........(token每过一段会更新，建议时常去原网站看看)
> （这就是一个 GUI 的小作业，更多是写着玩儿的

谢谢！我之前用的 `http://www.bjbus.com/home/ajax_rtbus_data.php` 这个接口，可以查到路线之类的信息。 另外，感觉你的接口数据解析部分，也许可以直接使用python自带的json包试试。
